/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ScanmemController */

#ifndef _Included_ScanmemController
#define _Included_ScanmemController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ScanmemController
 * Method:    sm_get_version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ScanmemController_sm_1get_1version
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
